---
name: Account Recovery
description: Initiate an account recovery due to lost 2FA or inability to access email address
title: Account recovery request
labels: account-recovery 

body:
- type: markdown
  attributes:
    value: |
      **Request for account recovery.**

- type: input
  attributes:
    label: PyPI Username
    description: >-
      Enter your PyPI `username` wrapped with single backticks
  validations:
    required: true

- type: textarea
  attributes:
    label: Reason for request
    description: |
      State the reason for your request
      - Lost access to email address
      - Lost 2FA authentication app or security token
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Recovery Codes
    description: |
      Every PyPI account generates eight recovery codes when 2FA is enabled, for use when the 2FA app or security token is lost. 
    options:
    - label: I never generated or have lost access to the recovery codes for my account
      required: true

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [PSF Code of Conduct][CoC] first.

      [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
    options:
    - label: I agree to follow the PSF Code of Conduct
      required: true

- type: checkboxes
  attributes:
    label: Acknowledgement
    description: |
      By their nature account recovery issues are labor intensive. The PyPI team has limited resources available for their completion.

      There may be a delay of a week or more between responses for these issues.
    options:
    - label: I understand that it may take a significant amount of time to process my account recovery request.
      required: true
...
