---
name: Size Limit Request (project-wide)
title: "Project Limit Request: PROJECT_NAME - 00 GiB"
description: "Your project has hit the total project size limit. (default: 10 GiB)"
labels: limit request

body:
  - type: markdown
    attributes:
      value: >
        If you can't upload your project's release to PyPI because you're
        hitting the total project size limit, we can sometimes increase your
        limit.

  - type: input
    attributes:
      label: Project URL
      placeholder: "https://pypi.org/project/<PROJECT_NAME>"
      description: |
        Provide a link to the PyPI page for the project in question.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Does this project already exist?
      description: |
        If it doesn't, maybe you're hitting the per-file limit?
      options:
        - label: "Yes" # should be a str but YAML parses unwrapped yes/no as bool
          required: true

  - type: input
    attributes:
      label: New limit
      description: |
        Please specify a new size limit, in gigabytes, that you want.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Update issue title
      description: >
        The title of this issue should be updated, to mention the project
        name and the requested new limit.
      options:
        - label: I have updated the title.
          required: true

  - type: dropdown
    attributes:
      label: Which indexes
      description: >-
        Which index/indexes you need the increase for?
        (PyPI, Test PyPI, or both)
      multiple: true
      options:
        - PyPI
        - TestPyPI
    validations:
      required: true

  # About the request
  - type: textarea
    attributes:
      label: About the project
      description: |
        What the project is and how long it has been active.

        If you expect your release sizes/total project size to increase in the future, mention it here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How large is each release?
      description: |
        Use MiB to describe the size, and provide a summary of what files are uploaded in each release.

        If you have made efforts to reduce the size of your PyPI releases, mention it here.
        If you bundle other packages in your project, mention it here.
        If you bundle example data in your project, mention it here.
      placeholder: |
        ~200 MiB total.

        2 Linux wheels at ~60 MiB, due to bundled libxml binaries.
        6 Windows/MacOS wheels at ~10 MiB.
        The source tarball at ~10 MiB.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How frequently do you make a release?
      placeholder: |
        Roughly once every three months.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: |
        Read the [PSF Code of Conduct][CoC] first.

        [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
      options:
        - label: I agree to follow the PSF Code of Conduct
          required: true
