---
name: Organizations Support
description: Get help with Organizations accounts
title: Organizations support
labels: organizations

body:
- type: markdown
  attributes:
    value: |
      **Request for support regarding Organization features of PyPI**

- type: input
  attributes:
    label: PyPI Username
    description: >-
      Enter your PyPI `username` wrapped with single backticks
  validations:
    required: true

- type: input
  attributes:
    label: PyPI Organization name
    description: >-
      Enter your PyPI `organization-name` wrapped with single backticks

- type: textarea
  attributes:
    label: Description of issue
    description: |
      Describe the issue you're having
  validations:
    required: true


- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [PSF Code of Conduct][CoC] first.

      [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
    options:
    - label: I agree to follow the PSF Code of Conduct
      required: true
...
