---
name: Name retention related request (PEP 541)
title: "PEP 541 Request: PROJECT_NAME"
description: You want to claim or flag a project in accordance to PEP 541
labels: PEP 541

body:
- type: markdown
  attributes:
    value: |
      [PEP 541] describes the workflow for any project claiming issues
      and conflict resolution. Make sure you **read and understand** the
      PEP to set your expectations on the possible outcomes.

      [PEP 541]: https://www.python.org/dev/peps/pep-0541/

- type: input
  attributes:
    label: Project to be claimed
    description: |
      Provide the name of the package and a link to its PyPI page

      Please also **update the issue title** as well.
    value: |
      `PROJECT_NAME`: https://pypi.org/project/PROJECT_NAME
  validations:
    required: true

- type: input
  attributes:
    label: Your PyPI username
    description: |
      To help moderators deal with the transfer please confirm your
      PyPI username
    value: |
      `USER_NAME`: https://pypi.org/user/USER_NAME
  validations:
    required: true

- type: textarea
  attributes:
    label: Reasons for the request
    description: |
      *Do you believe* the project has been abandoned or otherwise has
      issues that **justify this request**.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Maintenance or replacement?
    description: |
      If the transfer is successful, do you intend to continue
      maintenance of the package to or publish a different one?
    options:
    - Maintenance
    - Replacement

- type: textarea
  attributes:
    label: Source code repositories URLs
    description: |
      Please provide code repositories in regardless of the previous
      answer if possible.
  validations:
    required: false

- type: textarea
  attributes:
    label: Contact and additional research
    description: |
      Please document below any attempts to contact current owner and/or
      research you may have conducted.
  validations:
    required: true


- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [PSF Code of Conduct][CoC] first.

      [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
    options:
    - label: I agree to follow the PSF Code of Conduct
      required: true
...
